import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
const Header = () => {
    const [open, setOpen] = useState(false);
    return (_jsx("header", { id: "header", className: `flex w-full max-w-[1800px] p-2 items-center bg-white`, children: _jsx("div", { className: "w-full", children: _jsxs("div", { className: "relative -mx-4 flex items-center justify-between", children: [_jsx("div", { className: "w-60 max-w-full px-4", children: _jsxs("a", { href: "/#", className: "block w-full py-5", children: [_jsx("img", { src: "logo.svg", alt: "logo", className: "dark:hidden" }), _jsx("img", { src: "logo.svg", alt: "logo", className: "hidden dark:block" })] }) }), _jsxs("div", { className: "flex w-full items-center justify-between px-4", children: [_jsx("div", { children: _jsxs("button", { onClick: () => setOpen(!open), id: "navbarToggler", className: ` ${open && "navbarTogglerActive"} absolute right-4 top-1/2 block -translate-y-1/2 rounded-lg px-3 py-[6px] ring-primary focus:ring-2 lg:hidden`, children: [_jsx("span", { className: "relative my-[6px] block h-[2px] w-[30px] bg-black" }), _jsx("span", { className: "relative my-[6px] block h-[2px] w-[30px] bg-black" }), _jsx("span", { className: "relative my-[6px] block h-[2px] w-[30px] bg-black" })] }) }), _jsx("div", { className: "hidden justify-end pr-16 sm:flex lg:pr-0", children: _jsx("nav", { 
                                    // :className="!navbarOpen && 'hidden' "
                                    id: "navbarCollapse", className: `absolute right-4 top-full w-full max-w-[250px] rounded-lg bg-white px-6 py-5 shadow dark:bg-dark-2 lg:static lg:block lg:w-full lg:max-w-full lg:shadow-none lg:dark:bg-transparent ${!open && "hidden"} `, children: _jsxs("ul", { className: "block lg:flex", children: [_jsx(ListItem, { NavLink: "/#profile", children: "Sobre" }), _jsx(ListItem, { NavLink: "/#skills", children: "Skills" }), _jsx(ListItem, { NavLink: "/#", children: "About" }), _jsx(ListItem, { NavLink: "/#", children: "Contact" })] }) }) })] })] }) }) }));
};
export default Header;
const ListItem = ({ children, NavLink }) => {
    return (_jsx(_Fragment, { children: _jsx("li", { children: _jsx("a", { href: NavLink, className: "flex py-2 text-base font-medium text-body-color hover:text-dark dark:text-dark-6 text-black dark:hover:text-white lg:ml-12 lg:inline-flex", children: children }) }) }));
};
