import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const Footer = () => {
    return (_jsx(_Fragment, { children: _jsx("footer", { className: " w-full  bg-white pb-5 pt-5", children: _jsxs("div", { className: "flex flex-col max-w-[1800px] items-center", children: [_jsx("a", { href: "/#header", children: _jsx("img", { src: "public/logo.svg", alt: "logo", className: "w-64" }) }), _jsxs("div", { className: "flex flex-row w-full justify-center gap-4 p-4 md:p-0", children: [_jsx("div", { className: "w-[220px]", children: _jsxs(LinkGroup, { header: "Menu", children: [_jsx(NavLink, { link: "/#about", label: "Sobre" }), _jsx(NavLink, { link: "/#skills", label: "Skills" }), _jsx(NavLink, { link: "/#services", label: "Servi\u00E7os" }), _jsx(NavLink, { link: "/#projects", label: "Projetos" })] }) }), _jsx("div", { className: "flex flex-row w-[220px]", children: _jsx("div", { className: "w-full", children: _jsxs("div", { className: "w-full", children: [_jsx("h4", { className: "mb-4 text-lg font-semibold text-dark dark:text-white", children: "Contato" }), _jsxs("ul", { className: "space-y-3", children: [_jsx("li", { children: _jsx("a", { href: "tel:+5587996240263", className: "inline-block text-base leading-loose text-dark-4 hover:text-dark", children: "+55 (87) 99624-0263" }) }), _jsx("li", { children: _jsx("a", { href: "mailto:mateus.resende.r@gmail.com", className: "inline-block text-base leading-loose text-dark-4 hover:text-dark", children: "mateus.resende.r@gmail.com" }) }), _jsx("li", { children: _jsx("a", { href: "https://github.com/MateusResendeR", target: "_blank", rel: "noopener noreferrer", className: "inline-block text-base leading-loose text-dark-4 hover:text-dark", children: "GitHub" }) }), _jsx("li", { children: _jsx("a", { href: "https://www.linkedin.com/in/mateus-resende-05b349172", target: "_blank", rel: "noopener noreferrer", className: "inline-block text-base leading-loose text-dark-4 hover:text-dark", children: "LinkedIn" }) }), _jsx("li", { children: " \u00A0 " })] })] }) }) })] })] }) }) }));
};
export default Footer;
const LinkGroup = ({ children, header }) => {
    return (_jsx(_Fragment, { children: _jsx("div", { className: "w-full", children: _jsxs("div", { className: "w-full", children: [_jsx("h4", { className: " mb-4 text-lg font-semibold text-dark", children: header }), _jsx("ul", { className: "space-y-3", children: children })] }) }) }));
};
const NavLink = ({ link, label }) => {
    return (_jsx("li", { children: _jsx("a", { href: link, className: "inline-block text-base leading-loose text-dark-4 hover:text-dark", children: label }) }));
};
